/** Microscope 06 — SFT / annotation pipeline, LoRA / QLoRA, preference post-training branches. */
import { html, canvas, svg, field, stat, fmt } from './util.js';

export const id = 'scope-posttraining';
export const short = 'SFT · LoRA · DPO';
export const title = 'Post-training: annotation, LoRA and preference optimization';
export const description = 'SFT is a pipeline, not a box. Follow the annotation flow, size a LoRA adapter against full fine-tuning, and compare the reward-model + RLHF path with DPO-family optimization on the same preference data.';

const SFT = ['task taxonomy', 'prompt collection', 'target responses', 'annotator rubric', 'calibration', 'overlapping labels', 'adjudication', 'filtering', 'train / val split', 'chat template', 'tokenization', 'assistant loss mask', 'optimization'];
const SFT_NOTES = {
  'task taxonomy': 'Enumerate capabilities and domains to cover; drives sampling weights and gap analysis.',
  'prompt collection': 'Real usage logs (consented), written prompts, synthetic prompts; dedup and contamination checks against evals.',
  'target responses': 'Expert-written, model-assisted (draft then edit) or synthetic demonstrations; provenance tracked per example.',
  'annotator rubric': 'Explicit criteria (correctness, completeness, style, safety) with examples of each score level.',
  'calibration': 'Annotators label gold tasks with known answers until agreement clears a threshold.',
  'overlapping labels': 'A fraction of items get 2–3 independent labels to measure inter-annotator agreement (κ, α).',
  'adjudication': 'Disagreements escalate to senior reviewers; systematic disagreement feeds back into the rubric.',
  'filtering': 'Drop low-agreement, low-quality, refusal-heavy or contaminated items; quality beats quantity at this stage.',
  'train / val split': 'Split by prompt cluster, not by row, so near-duplicates do not leak across the boundary.',
  'chat template': 'Role markers and special tokens serialised byte-exactly the way serving will do it.',
  'tokenization': 'The same tokenizer as pre-training; check that template tokens are single ids.',
  'assistant loss mask': 'Loss only on assistant tokens (labels = −100 elsewhere); the end-of-turn token stays unmasked.',
  'optimization': 'Small LR (1e-5 range, illustrative), 1–3 epochs, mixed replay of pre-training data to limit catastrophic forgetting.',
};

export function mount(root) {
  root.innerHTML = '';
  root.appendChild(html(`
    <h4 class="ctl-label">SFT / annotation pipeline · click a stage</h4>
    <div id="sft-flow"></div>
    <div class="panel-desc" id="sft-note" aria-live="polite"></div>
    <div class="kv-list" style="margin-top:.6rem">
      <div><b>Model-assisted annotation</b><span>A model drafts, a human edits: faster, but drafts anchor annotators and can leak the drafting model's style.</span></div>
      <div><b>Synthetic demonstrations</b><span>Generated by stronger models with verification (unit tests, checkers, judges); needs contamination and diversity control.</span></div>
      <div><b>Quality vs quantity</b><span>Thousands of excellent demonstrations often beat hundreds of thousands of mediocre ones for format and behaviour.</span></div>
      <div><b>Catastrophic forgetting</b><span>Narrow SFT erodes base capabilities; replay a slice of pre-training or general data and keep LR low.</span></div>
    </div>

    <div class="scope-grid" style="margin-top:1.4rem">
      <div>
        <h4 class="ctl-label">LoRA sizing</h4>
        <div id="lora-vis"></div>
        <div class="scope-controls" id="lora-ctl"></div>
        <div class="stat-row" id="lora-stats"></div>
      </div>
      <div class="panel-desc">
        <p><b>Low-rank adaptation.</b> The base weight <code>W</code> is frozen. Two small trainable matrices <code>A ∈ ℝ^{r×d_in}</code> and <code>B ∈ ℝ^{d_out×r}</code> give <code>W' = W + (α/r)·B·A</code>. <code>B</code> starts at zero so training begins from the base model. Rank <code>r</code> and scaling <code>α</code> are the main knobs; target modules are commonly the attention projections and MLP matrices.</p>
        <p><b>Adapter storage and serving.</b> Adapters are megabytes, not gigabytes. They can be merged into <code>W</code> (identical inference cost to the base model) or kept separate and applied as an extra small matmul so many adapters can share one resident base (multi-LoRA serving). LoRA does not make inference faster.</p>
        <p><b>QLoRA.</b> The frozen base is stored quantized (4-bit NF4 with double quantization, as described in the QLoRA paper); adapters stay in higher precision and are trained through dequantized weights. This cuts adaptation memory substantially at the cost of on-the-fly dequantization compute.</p>
      </div>
    </div>

    <div style="margin-top:1.4rem">
      <h4 class="ctl-label">Preference post-training · two paths from the same data</h4>
      <div id="pref-vis"></div>
      <div class="two">
        <div class="panel-desc"><p><b>Reward model + RLHF (PPO-style).</b> Train a reward model on chosen/rejected pairs (Bradley–Terry loss on a scalar head), then optimise the policy against it with PPO, adding a KL penalty <code>β·KL(π ‖ π_ref)</code> to a frozen reference policy and a value model for advantages. Needs online sampling from the policy every step: expensive, but can exploit any reward signal, including verifiable rewards. GRPO-style variants drop the value model and normalise advantages within a group of samples.</p></div>
        <div class="panel-desc"><p><b>DPO family.</b> Skip the reward model: optimise <code>−log σ(β[(log π(y_w|x) − log π_ref(y_w|x)) − (log π(y_l|x) − log π_ref(y_l|x))])</code> directly on pairs. Offline, stable, cheap (one forward for policy and one for reference per pair), but limited to the pairs you have; IPO, KTO and ORPO are variants with different loss shapes.</p></div>
      </div>
      <div class="kv-list">
        <div><b>Reward hacking</b><span>The policy finds reward-model blind spots (length, confident tone, formatting) that raise reward without raising quality.</span></div>
        <div><b>Verbosity bias</b><span>Judges and reward models prefer longer answers; control with length-normalised rewards or length-matched pairs.</span></div>
        <div><b>Judge bias</b><span>LLM judges prefer their own style and position; randomise order and calibrate against human labels.</span></div>
        <div><b>Sycophancy</b><span>Optimising for approval teaches agreement with the user over correctness; needs adversarial pairs.</span></div>
        <div><b>Over-refusal</b><span>Safety pairs without matched benign pairs teach refusing everything near the boundary.</span></div>
        <div><b>Reference drift</b><span>Too small a β lets the policy drift far from the reference and lose capabilities; too large stalls learning.</span></div>
      </div>
    </div>
  `));

  // SFT flow
  const flow = root.querySelector('#sft-flow'), snote = root.querySelector('#sft-note');
  let sel = 0;
  const drawFlow = () => {
    flow.innerHTML = '';
    const per = 7, rows = Math.ceil(SFT.length / per), W = 760, rh = 52, s = canvas(W, rows * rh, 'SFT pipeline');
    const w = W / per;
    SFT.forEach((t, i) => {
      const r = Math.floor(i / per), c = i % per, x = c * w + 3, y = r * rh + 8;
      const g = svg('g', { role: 'button', tabindex: 0, 'aria-label': t, 'aria-pressed': i === sel ? 'true' : 'false', style: 'cursor:pointer' }, s);
      svg('rect', { class: 'box sub-posttraining' + (i === sel ? ' on' : ''), x, y, width: w - 6, height: 30, rx: 4 }, g);
      const tx = svg('text', { class: 'tiny', x: x + (w - 6) / 2, y: y + 19, 'text-anchor': 'middle' }, g, t); tx.style.fontSize = '9px';
      if (i < SFT.length - 1) { if (c < per - 1) svg('path', { class: 'arrow', d: `M${x + w - 6} ${y + 15} L${x + w} ${y + 15}` }, s); else svg('path', { class: 'arrow', d: `M${x + (w - 6) / 2} ${y + 30} V${y + rh - 2}` }, s); }
      const pick = () => { sel = i; drawFlow(); };
      g.addEventListener('click', pick); g.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); pick(); } });
    });
    flow.appendChild(s);
    snote.innerHTML = `<p><b>${SFT[sel]}.</b> ${SFT_NOTES[SFT[sel]]}</p>`;
  };
  drawFlow();

  // LoRA
  const lctl = root.querySelector('#lora-ctl'), lstats = root.querySelector('#lora-stats'), lvis = root.querySelector('#lora-vis');
  const lf = {
    d: field({ id: 'lora-d', label: 'd_model', value: 4096, min: 256, max: 32768, step: 256 }),
    r: field({ id: 'lora-r', label: 'rank r', type: 'range', value: 16, min: 1, max: 256, step: 1 }),
    layers: field({ id: 'lora-L', label: 'layers', value: 32, min: 1, max: 200 }),
    mods: field({ id: 'lora-m', label: 'target modules', type: 'select', value: '4', options: [['2', 'q, v'], ['4', 'q, k, v, o'], ['7', 'attention + MLP (7)']] }),
    params: field({ id: 'lora-p', label: 'base params (B)', value: 8, min: 0.1, max: 2000, step: 0.1 }),
  };
  Object.values(lf).forEach(x => { lctl.appendChild(x.el); x.input.addEventListener('input', updLora); });
  function updLora() {
    const d = +lf.d.input.value, r = +lf.r.input.value, L = +lf.layers.input.value, mods = +lf.mods.input.value, P = +lf.params.input.value * 1e9;
    const per = r * (d + d); // A: r×d_in, B: d_out×r with d_in≈d_out≈d (illustrative)
    const total = per * mods * L;
    lstats.innerHTML = stat('trainable params', fmt(total)) + stat('fraction of base', (100 * total / P).toFixed(3) + '%') + stat('adapter (BF16)', (total * 2 / 1e6).toFixed(1) + ' MB') + stat('full FT optimizer state', (P * 16 / 1e9).toFixed(0) + ' GB');
    lvis.innerHTML = '';
    const s = canvas(420, 130, 'W plus B times A');
    svg('rect', { class: 'box', x: 10, y: 20, width: 90, height: 90, rx: 4 }, s); svg('text', { x: 55, y: 60, 'text-anchor': 'middle' }, s, 'W'); svg('text', { class: 'tiny mut', x: 55, y: 76, 'text-anchor': 'middle' }, s, 'frozen d×d');
    svg('text', { x: 118, y: 70 }, s, '+');
    const rw = Math.max(4, Math.min(40, r / 4));
    svg('rect', { class: 'box sub-posttraining', x: 140, y: 20, width: rw, height: 90, rx: 3, style: 'fill:var(--atlas-posttraining)' }, s); svg('text', { class: 'tiny', x: 140 + rw / 2, y: 118, 'text-anchor': 'middle' }, s, 'B d×r');
    svg('text', { x: 190 + rw - 10, y: 70 }, s, '×');
    svg('rect', { class: 'box', x: 215 + rw, y: 20, width: 90, height: rw, rx: 3, style: 'fill:var(--atlas-posttraining)' }, s); svg('text', { class: 'tiny', x: 260 + rw, y: 34 + rw, 'text-anchor': 'middle' }, s, 'A r×d');
    svg('text', { class: 'tiny mut', x: 320 + rw, y: 70 }, s, `scale α/r`);
    lvis.appendChild(s);
  }
  updLora();

  // preference branches
  const pv = root.querySelector('#pref-vis');
  const s = canvas(760, 150, 'Preference data feeding RLHF and DPO paths');
  const box = (x, y, w, t, cls = '') => { svg('rect', { class: 'box ' + cls, x, y, width: w, height: 30, rx: 4 }, s); svg('text', { class: 'tiny', x: x + w / 2, y: y + 19, 'text-anchor': 'middle' }, s, t); };
  box(10, 60, 90, 'prompt'); box(120, 60, 130, 'candidate responses'); box(270, 60, 130, 'chosen / rejected', 'sub-posttraining');
  svg('path', { class: 'arrow', d: 'M100 75 H118' }, s); svg('path', { class: 'arrow', d: 'M250 75 H268' }, s);
  box(440, 14, 120, 'reward model'); box(580, 14, 170, 'PPO + KL(π‖π_ref) + value');
  box(440, 106, 310, 'DPO loss on (π, π_ref) log-ratios — no reward model');
  svg('path', { class: 'arrow', d: 'M400 75 C420 75 420 29 438 29' }, s); svg('path', { class: 'arrow', d: 'M560 29 H578' }, s); svg('path', { class: 'arrow', d: 'M400 75 C420 75 420 121 438 121' }, s);
  svg('text', { class: 'tiny mut', x: 420, y: 10 }, s, 'online: sample from policy each step');
  svg('text', { class: 'tiny mut', x: 420, y: 148 }, s, 'offline: pairs only');
  pv.appendChild(s);
}
